name: $(Build.DefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Deploy_ARM_Template
    displayName: Deploy_ARM_Template
    jobs:
    - job: 
      steps: 
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)\iac\'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)\artifacts'
          
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)\artifacts'
          ArtifactName: 'artifact'
          publishLocation: pipeline
        
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Subscription'
          azureResourceManagerConnection: 'Visual Studio Ultimate with MSDN(Subscription)'
          subscriptionId: 'Subscription'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.ArtifactStagingDirectory)\artifacts\policy.json'
          csmParametersFile: '$(Build.ArtifactStagingDirectory)\artifacts\policy.parameters.json'
          deploymentMode: 'Incremental'
