name: $(Build.DefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Deploy_ARM_Template
    displayName: Deploy_ARM_Template
    jobs:
    - job: 
      steps: 
 